export const Colors = {
      dark: '#000',
      white: '#fff',
      black: '#111',
      primary: '#001033',
      secondary: '#0FBCF5',
      grey: '#3E3E3E',
      disabledGrey: '#DBDBDB',
      greyBorderColor: '#CBCBCB',
      greyTextColor: '#676767',
      background: '#F0F0F0',
      iconDisabled: '#989EAC',
      backgroundListColor: '#F4F4F4',
      backgroundPointsView: '#E9ECF4',
      negativeBackgroundPointsView: '#F4F1E9',
      lightGrey: '#E6E6E6',
      transparent: 'transparent',
      dateTextColor: '#ADADAD',
      lynxWhite: '#f7f7f7',
      lightGreyText: '#A0A0A0',
      red: '#FF0000',
      iconGenderBorder: '#E5E5E5',
      optionalColor: '#CCCCCC',
      gold: '#C7AC16',
      separatorGrey: '#C5CCDD',
      gaugeGrey: '#EDEDF5',
      gaugePointsGrey: '#9797B4',
      blueForMemberList: '#0F214A',
      downloadCardColor: '#68799A',
      negativeTextPointsView: '#CC5430',
      mapSeparatorGrey: '#D1D1D1',
      green: '#9cd6a3'
    }
    